### PR TITLE
Added PR and issue templates for GitHub

### PR DESCRIPTION
**Pull request by webmozart**
This PR copies over the PR and issue templates from the [sulu-io/sulu](/sulu-io/sulu) repository.

### CODE REVIEW

**Comment by webmozart** [comment]
I'll include https://github.com/sulu-io/sulu/pull/2111 and https://github.com/sulu-io/sulu/pull/2112 here as soon as they are merged.

**Comment by danrot** [comment]
Thank you :-)

**Comment by danrot** [comment]
Oops, have overseen your last comment :confused: Sry about that, do you create another PR for these changes?

**Comment by webmozart** [comment]
see #647

**Pull request merged**
