### PR TITLE
updated translations and composer

### PR DESCRIPTION
**Pull request by danrot**
__tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes https://github.com/sulu-io/sulu/issues/888
| BC breaks        | UI text changes
| Documentation PR | none

### CODE REVIEW

**Comment by liuggio** [comment]
is the translation broken?

**Comment by danrot** [comment]
No, we just changed one translation :wink:

**Comment by liuggio** [comment]
thanks @danrot ...

**Comment by danrot** [comment]
@liuggio Ah, I am sry, we don't really use the TranslationBundle, because especially the UI is pretty broken.

**Pull request merged**
